controller_manager:
  ros__parameters:
    update_rate: 500

    dog_controller:
      type: dog_controller/DogController

dog_controller:
  ros__parameters:
    target_topic: joint_states
    joints:
      - yuntai
      - left1
      - left2
      - left3
      - right1
      - right2
      - right3
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort

    joint1_kp: 80.0
    joint1_kd: 3.0
    joint2_kp: 50.0
    joint2_kd: 2.0
    joint3_kp: 50.0
    joint3_kd: 2.0
    joint4_kp: 35.0
    joint4_kd: 1.5
    joint5_kp: 50.0
    joint5_kd: 2.0
    joint6_kp: 50.0
    joint6_kd: 2.0
    joint7_kp: 35.0
    joint7_kd: 1.5
    joint_torque_filter_gate: 0.8
    joint_omega_filter_gate: 0.8
    command_effort_limit: 10.0
